export {
  TAG_CATEGORIES,
  COMPACT_TAG_CATEGORIES,
  HEAT_LABELS,
  CALORIE_OPTIONS,
  DEFAULT_HEAT_LABELS,
  DEFAULT_HEAT_ICONS,
  DEFAULT_HEAT_BG,
  DEFAULT_HEAT_BORDER,
  DEFAULT_HEAT_COLOR,
  MIN_SPICE_SCALE_LEVELS,
  MAX_SPICE_SCALE_LEVELS,
  SPICE_LABEL_MIN,
  SPICE_LABEL_MAX,
} from './food-tags';
export { COLOR_WARNING, COLOR_WARNING_BG, COLOR_WARNING_BG_SM, COLOR_WARNING_TEXT, COLOR_SUCCESS, COLOR_ERROR, COLOR_ERROR_MUTED, COLOR_BRAND_SOLID, COLOR_BRAND_HOVER } from './colors';
